import = ["~/.config/alacritty/alacritty-master/dracula.toml", "~/.config/alacritty/xdg_env.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 1
y = 0

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
startup_mode = "Fullscreen"
title = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
